// Barcode Scanning Interceptor
// Listens for rapid keyboard input usually generated by a hardware barcode scanner
window.BarcodeScanner = {
    buffer: '',
    lastTime: 0,
    timeout: 100, // Ms threshold between keystrokes to be considered a scanner

    init: function() {
        document.addEventListener('keypress', (e) => {
            // Only intercept if we are on the POS view and not typing in an input field (except the main search)
            if (window.location.hash !== '#/pos' && window.location.hash !== '') return;
            
            const activeTag = document.activeElement.tagName.toLowerCase();
            const activeId = document.activeElement.id;
            
            // Allow typing in the search bar without breaking, but still capture enter
            if (activeTag === 'input' && activeId !== 'pos-search') return;

            const currentTime = new Date().getTime();
            
            if (currentTime - this.lastTime > this.timeout) {
                this.buffer = ''; // Reset if too much time passed
            }
            
            if (e.key === 'Enter') {
                if (this.buffer.length > 0) {
                    window.POS.handleBarcodeScan(this.buffer);
                    this.buffer = '';
                    e.preventDefault(); // Prevent form submission if focused on search
                }
            } else {
                this.buffer += e.key;
            }
            
            this.lastTime = currentTime;
        });
    }
};

// Initialize scanner globally
document.addEventListener('DOMContentLoaded', () => {
    window.BarcodeScanner.init();
});
